In [1]:
# !pip install pandas
# !pip install numpy
# !pip install scipy
# !pip install openpyxl 
# !pip install scikit_posthocs

import pandas as pd
from scipy.stats import friedmanchisquare

In [2]:
# Read the resulst from the excel file

#SET A
df_A_R1 = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="Total Results",
    usecols="M:R",
    skiprows=11,
    names=["JSON","PlantUML","PlantUMLx2","PlantUMLx10","JSONx2","JSONx10"],
    nrows=5
)

df_A_R2 = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="Total Results",
    usecols="M:R",
    skiprows=19,
    names=["JSON","PlantUML","PlantUMLx2","PlantUMLx10","JSONx2","JSONx10"],
    nrows=5
)

df_A_R3 = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="Total Results",
    usecols="M:R",
    skiprows=27,
    names=["JSON","PlantUML","PlantUMLx2","PlantUMLx10","JSONx2","JSONx10"],
    nrows=5
)

df_A_R4 = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="Total Results",
    usecols="M:R",
    skiprows=35,
    names=["JSON","PlantUML","PlantUMLx2","PlantUMLx10","JSONx2","JSONx10"],
    nrows=5
)

df_A_R5 = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="Total Results",
    usecols="M:R",
    skiprows=43,
    names=["JSON","PlantUML","PlantUMLx2","PlantUMLx10","JSONx2","JSONx10"],
    nrows=5
)

#SET B
df_B_R1 = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="Total Results",
    usecols="S:T",
    skiprows=11,
    names=["JSON-LM","PlantUML-LM"],
    nrows=5
)

df_B_R2 = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="Total Results",
    usecols="S:T",
    skiprows=19,
    names=["JSON-LM","PlantUML-LM"],
    nrows=5
)

df_B_R3 = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="Total Results",
    usecols="S:T",
    skiprows=27,
    names=["JSON-LM","PlantUML-LM"],
    nrows=5
)

df_B_R4 = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="Total Results",
    usecols="S:T",
    skiprows=35,
    names=["JSON-LM","PlantUML-LM"],
    nrows=5
)

df_B_R5 = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="Total Results",
    usecols="S:T",
    skiprows=43,
    names=["JSON-LM","PlantUML-LM"],
    nrows=5
)

df_prov_A = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="per provider",
    usecols="B:G",
    skiprows=36,
    names=["PlantUML","PlantUMLx2","PlantUMLx10","JSON","JSONx2","JSONx10"],
    nrows=5
)

df_prov_B = pd.read_excel(
    "TotalResults-gpt5.xlsx",
    sheet_name="per provider",
    usecols="H:I",
    skiprows=36,
    names=["PlantUML-LM","JSON-LM"],
    nrows=5
)

df_A_R1.index = ["25%","50%","75%","100%"]
df_A_R1

       JSON  PlantUML  PlantUMLx2  PlantUMLx10  JSONx2  JSONx10
25%   0.972     0.972       0.944        0.888   0.888    0.852
50%   0.972     0.944       0.917        0.861   0.888    0.852
75%   0.944     0.917       0.888        0.861   0.806    0.777
100%  0.917     0.917       0.888        0.861   0.806    0.740

In [3]:
df_A_R2.index = ["25%","50%","75%","100%"]
df_A_R2

          JSON  PlantUML  PlantUMLx2  PlantUMLx10    JSONx2   JSONx10
25%   0.944444  1.000000    0.972222     0.944444  0.861111  0.851852
50%   0.916667  1.000000    0.972222     0.888889  0.861111  0.777778
75%   0.833333  0.944444    0.972222     0.888889  0.833333  0.740741
100%  0.833333  0.888889    0.944444     0.888889  0.750000  0.740741

In [4]:
df_A_R3.index = ["25%","50%","75%","100%"]
df_A_R3

          JSON  PlantUML  PlantUMLx2  PlantUMLx10    JSONx2   JSONx10
25%   0.944444  1.000000    0.972222     0.916667  0.861111  0.814815
50%   0.944444  1.000000    0.972222     0.916667  0.851852  0.814815
75%   0.916667  0.972222    0.944444     0.916667  0.805556  0.777778
100%  0.861111  0.944444    0.944444     0.888889  0.777778  0.740741

In [5]:
df_A_R4.index = ["25%","50%","75%","100%"]
df_A_R4

          JSON  PlantUML  PlantUMLx2  PlantUMLx10    JSONx2   JSONx10
25%   0.944444  1.000000    0.972222     0.916667  0.861111  0.916667
50%   0.916667  0.972222    0.972222     0.888889  0.814815  0.777778
75%   0.888889  0.972222    0.916667     0.861111  0.814815  0.777778
100%  0.861111  0.944444    0.944444     0.861111  0.777778  0.740741

In [6]:
df_A_R5.index = ["25%","50%","75%","100%"]
df_A_R5

          JSON  PlantUML  PlantUMLx2  PlantUMLx10    JSONx2   JSONx10
25%   0.972222  1.000000    0.972222     0.944444  0.861111  0.851852
50%   0.944444  1.000000    0.972222     0.888889  0.833333  0.777778
75%   0.888889  0.972222    0.888889     0.833333  0.722222  0.740741
100%  0.861111  0.944444    0.888889     0.805556  0.750000  0.740741

In [7]:
df_B_R1.index = ["25%","50%","75%","100%"]
df_B_R1

      JSON-LM  PlantUML-LM
25%     0.958        1.000
50%     0.916        0.875
75%     0.458        0.625
100%    0.291        0.458

In [8]:
df_B_R2.index = ["25%","50%","75%","100%"]
df_B_R2

       JSON-LM  PlantUML-LM
25%   0.958333     1.000000
50%   0.833333     0.875000
75%   0.458333     0.583333
100%  0.291667     0.458333

In [9]:
df_B_R3.index = ["25%","50%","75%","100%"]
df_B_R3

       JSON-LM  PlantUML-LM
25%   0.958333     0.958333
50%   0.791667     0.875000
75%   0.416667     0.583333
100%  0.291667     0.458333

In [10]:
df_B_R4.index = ["25%","50%","75%","100%"]
df_B_R4

       JSON-LM  PlantUML-LM
25%   0.958333     1.000000
50%   0.875000     0.875000
75%   0.458333     0.666667
100%  0.250000     0.458333

In [11]:
df_B_R5.index = ["25%","50%","75%","100%"]
df_B_R5

       JSON-LM  PlantUML-LM
25%   0.916667     0.958333
50%   0.833333     0.875000
75%   0.458333     0.583333
100%  0.250000     0.458333

In [12]:
df_prov_A.index = ["gem-2.5-fl","gem-2.5-pro","gpt4o-mini","gpt5-mini"]
df_prov_A = df_prov_A.T
df_prov_A = df_prov_A.dropna()
df_prov_A

             gem-2.5-fl  gem-2.5-pro  gpt4o-mini  gpt5-mini
PlantUML       0.933333     0.977778    0.955556   1.000000
PlantUMLx2     0.861111     0.977778    0.944444   1.000000
PlantUMLx10    0.805556     0.988889    0.788889   0.988889
JSON           0.911111     0.955556    0.816667   0.988889
JSONx2         0.788889     0.844444    0.838889   0.877778

In [13]:
df_prov_B.index = ["gem-2.5-fl","gem-2.5-pro","gpt4o-mini","gpt5-mini"]
df_prov_B = df_prov_B.T
df_prov_B

             gem-2.5-fl  gem-2.5-pro  gpt4o-mini  gpt5-mini
PlantUML-LM    0.666667     0.866667    0.541667   0.916667
JSON-LM        0.375000     0.750000    0.550000   0.850000

In [14]:
# create dataframes for different thresholds with different formats in colums and runs in rows.
dfs_A = [df_A_R1, df_A_R2, df_A_R3, df_A_R4, df_A_R5]

df_A_25 = pd.concat([df.iloc[[0]] for df in dfs_A], ignore_index=True)
df_A_50 = pd.concat([df.iloc[[1]] for df in dfs_A], ignore_index=True)
df_A_75 = pd.concat([df.iloc[[2]] for df in dfs_A], ignore_index=True)
df_A_100 = pd.concat([df.iloc[[3]] for df in dfs_A], ignore_index=True)

dfs_B = [df_B_R1, df_B_R2, df_B_R3, df_B_R4, df_B_R5]

df_B_25 = pd.concat([df.iloc[[0]] for df in dfs_B], ignore_index=True)
df_B_50 = pd.concat([df.iloc[[1]] for df in dfs_B], ignore_index=True)
df_B_75 = pd.concat([df.iloc[[2]] for df in dfs_B], ignore_index=True)
df_B_100 = pd.concat([df.iloc[[3]] for df in dfs_B], ignore_index=True)

In [15]:
df_A_25

       JSON  PlantUML  PlantUMLx2  PlantUMLx10    JSONx2   JSONx10
0  0.972000     0.972    0.944000     0.888000  0.888000  0.852000
1  0.944444     1.000    0.972222     0.944444  0.861111  0.851852
2  0.944444     1.000    0.972222     0.916667  0.861111  0.814815
3  0.944444     1.000    0.972222     0.916667  0.861111  0.916667
4  0.972222     1.000    0.972222     0.944444  0.861111  0.851852

In [16]:
df_A_50

       JSON  PlantUML  PlantUMLx2  PlantUMLx10    JSONx2   JSONx10
0  0.972000  0.944000    0.917000     0.861000  0.888000  0.852000
1  0.916667  1.000000    0.972222     0.888889  0.861111  0.777778
2  0.944444  1.000000    0.972222     0.916667  0.851852  0.814815
3  0.916667  0.972222    0.972222     0.888889  0.814815  0.777778
4  0.944444  1.000000    0.972222     0.888889  0.833333  0.777778

In [17]:
df_A_75

       JSON  PlantUML  PlantUMLx2  PlantUMLx10    JSONx2   JSONx10
0  0.944000  0.917000    0.888000     0.861000  0.806000  0.777000
1  0.833333  0.944444    0.972222     0.888889  0.833333  0.740741
2  0.916667  0.972222    0.944444     0.916667  0.805556  0.777778
3  0.888889  0.972222    0.916667     0.861111  0.814815  0.777778
4  0.888889  0.972222    0.888889     0.833333  0.722222  0.740741

In [18]:
df_A_100

       JSON  PlantUML  PlantUMLx2  PlantUMLx10    JSONx2   JSONx10
0  0.917000  0.917000    0.888000     0.861000  0.806000  0.740000
1  0.833333  0.888889    0.944444     0.888889  0.750000  0.740741
2  0.861111  0.944444    0.944444     0.888889  0.777778  0.740741
3  0.861111  0.944444    0.944444     0.861111  0.777778  0.740741
4  0.861111  0.944444    0.888889     0.805556  0.750000  0.740741

In [19]:
df_B_25

    JSON-LM  PlantUML-LM
0  0.958000     1.000000
1  0.958333     1.000000
2  0.958333     0.958333
3  0.958333     1.000000
4  0.916667     0.958333

In [20]:
df_B_50

    JSON-LM  PlantUML-LM
0  0.916000        0.875
1  0.833333        0.875
2  0.791667        0.875
3  0.875000        0.875
4  0.833333        0.875

In [21]:
df_B_75

    JSON-LM  PlantUML-LM
0  0.458000     0.625000
1  0.458333     0.583333
2  0.416667     0.583333
3  0.458333     0.666667
4  0.458333     0.583333

In [22]:
df_B_100

    JSON-LM  PlantUML-LM
0  0.291000     0.458000
1  0.291667     0.458333
2  0.291667     0.458333
3  0.250000     0.458333
4  0.250000     0.458333

In [23]:
# RQ2.1: compare formats > wilcoxon test per threshold and size (no significant results)

In [24]:
#only for smallest models
from scipy.stats import wilcoxon

stat25, p25 = wilcoxon(df_A_25["PlantUML"], df_A_25["JSON"])
stat50, p50 = wilcoxon(df_A_50["PlantUML"], df_A_50["JSON"])
stat75, p75 = wilcoxon(df_A_75["PlantUML"], df_A_75["JSON"])
stat100, p100 = wilcoxon(df_A_100["PlantUML"], df_A_100["JSON"])

print("PlantUML vs JSON at 25% threshold")
print("Statistic:", stat25)
print("p-value:", p25)
print("PlantUML vs JSON at 50% threshold")
print("Statistic:", stat50)
print("p-value:", p50)
print("PlantUML vs JSON at 75% threshold")
print("Statistic:", stat75)
print("p-value:", p75)
print("PlantUML vs JSON at 100% threshold")
print("Statistic:", stat100)
print("p-value:", p100)

PlantUML vs JSON at 25% threshold
Statistic: 0.0
p-value: 0.125
PlantUML vs JSON at 50% threshold
Statistic: 1.0
p-value: 0.125
PlantUML vs JSON at 75% threshold
Statistic: 1.0
p-value: 0.125
PlantUML vs JSON at 100% threshold
Statistic: 0.0
p-value: 0.125

In [25]:
#only for x2 models

stat25, p25 = wilcoxon(df_A_25["PlantUMLx2"], df_A_25["JSONx2"])
stat50, p50 = wilcoxon(df_A_50["PlantUMLx2"], df_A_50["JSONx2"])
stat75, p75 = wilcoxon(df_A_75["PlantUMLx2"], df_A_75["JSONx2"])
stat100, p100 = wilcoxon(df_A_100["PlantUMLx2"], df_A_100["JSONx2"])

print("PlantUML vs JSON at 25% threshold")
print("Statistic:", stat25)
print("p-value:", p25)
print("PlantUML vs JSON at 50% threshold")
print("Statistic:", stat50)
print("p-value:", p50)
print("PlantUML vs JSON at 75% threshold")
print("Statistic:", stat75)
print("p-value:", p75)
print("PlantUML vs JSON at 100% threshold")
print("Statistic:", stat100)
print("p-value:", p100)

PlantUML vs JSON at 25% threshold
Statistic: 0.0
p-value: 0.0625
PlantUML vs JSON at 50% threshold
Statistic: 0.0
p-value: 0.0625
PlantUML vs JSON at 75% threshold
Statistic: 0.0
p-value: 0.0625
PlantUML vs JSON at 100% threshold
Statistic: 0.0
p-value: 0.0625

In [26]:
#only for x10 models

stat25, p25 = wilcoxon(df_A_25["PlantUMLx10"], df_A_25["JSONx10"])
stat50, p50 = wilcoxon(df_A_50["PlantUMLx10"], df_A_50["JSONx10"])
stat75, p75 = wilcoxon(df_A_75["PlantUMLx10"], df_A_75["JSONx10"])
stat100, p100 = wilcoxon(df_A_100["PlantUMLx10"], df_A_100["JSONx10"])

print("PlantUML vs JSON at 25% threshold")
print("Statistic:", stat25)
print("p-value:", p25)
print("PlantUML vs JSON at 50% threshold")
print("Statistic:", stat50)
print("p-value:", p50)
print("PlantUML vs JSON at 75% threshold")
print("Statistic:", stat75)
print("p-value:", p75)
print("PlantUML vs JSON at 100% threshold")
print("Statistic:", stat100)
print("p-value:", p100)

PlantUML vs JSON at 25% threshold
Statistic: 0.0
p-value: 0.125
PlantUML vs JSON at 50% threshold
Statistic: 0.0
p-value: 0.0625
PlantUML vs JSON at 75% threshold
Statistic: 0.0
p-value: 0.0625
PlantUML vs JSON at 100% threshold
Statistic: 0.0
p-value: 0.0625

In [27]:
#only for Set B models

stat25, p25 = wilcoxon(df_B_25["PlantUML-LM"], df_B_25["JSON-LM"])
stat50, p50 = wilcoxon(df_B_50["PlantUML-LM"], df_B_50["JSON-LM"])
stat75, p75 = wilcoxon(df_B_75["PlantUML-LM"], df_B_75["JSON-LM"])
stat100, p100 = wilcoxon(df_B_100["PlantUML-LM"], df_B_100["JSON-LM"])

print("PlantUML vs JSON at 25% threshold")
print("Statistic:", stat25)
print("p-value:", p25)
print("PlantUML vs JSON at 50% threshold")
print("Statistic:", stat50)
print("p-value:", p50)
print("PlantUML vs JSON at 75% threshold")
print("Statistic:", stat75)
print("p-value:", p75)
print("PlantUML vs JSON at 100% threshold")
print("Statistic:", stat100)
print("p-value:", p100)

PlantUML vs JSON at 25% threshold
Statistic: 0.0
p-value: 0.125
PlantUML vs JSON at 50% threshold
Statistic: 1.0
p-value: 0.25
PlantUML vs JSON at 75% threshold
Statistic: 0.0
p-value: 0.0625
PlantUML vs JSON at 100% threshold
Statistic: 0.0
p-value: 0.0625

In [28]:
# RQ2.2: compare size > friedman test per threshold and format in set A (significant difference between PlantUML and PlantUMLx10 and between JSON and JSONx10 for all thresholds)

In [29]:
#only for plantUML:
df_A_25_PlantUML = df_A_25.loc[:,["PlantUML","PlantUMLx2","PlantUMLx10"]]
df_A_50_PlantUML = df_A_50.loc[:,["PlantUML","PlantUMLx2","PlantUMLx10"]]
df_A_75_PlantUML = df_A_75.loc[:,["PlantUML","PlantUMLx2","PlantUMLx10"]]
df_A_100_PlantUML = df_A_100.loc[:,["PlantUML","PlantUMLx2","PlantUMLx10"]]


df_A_25_PlantUML

   PlantUML  PlantUMLx2  PlantUMLx10
0     0.972    0.944000     0.888000
1     1.000    0.972222     0.944444
2     1.000    0.972222     0.916667
3     1.000    0.972222     0.916667
4     1.000    0.972222     0.944444

In [30]:
stat, p = friedmanchisquare(*[df_A_25_PlantUML[col] for col in df_A_25_PlantUML.columns])

# get dimensions
n = df_A_25_PlantUML.shape[0]
k = df_A_25_PlantUML.shape[1]

# effect size
W = stat / (n * (k - 1))

print("SET A - TRHESHOLD: 25% for all size of plantUML")
print("Friedman statistic:", stat)
print("p-value:", f"{p:.6f}")
print("Kendall's W:", W)

SET A - TRHESHOLD: 25% for all size of plantUML
Friedman statistic: 10.0
p-value: 0.006738
Kendall's W: 1.0

In [31]:
stat, p = friedmanchisquare(*[df_A_50_PlantUML[col] for col in df_A_50_PlantUML.columns])

# get dimensions
n = df_A_50_PlantUML.shape[0]
k = df_A_50_PlantUML.shape[1]

# effect size
W = stat / (n * (k - 1))

print("SET A - THRESHOLD: 50% for all size of plantUML")
print("Friedman statistic:", stat)
print("p-value:", f"{p:.6f}")
print("Kendall's W:", W)

SET A - THRESHOLD: 50% for all size of plantUML
Friedman statistic: 9.578947368421062
p-value: 0.008317
Kendall's W: 0.9578947368421062

In [32]:
stat, p = friedmanchisquare(*[df_A_75_PlantUML[col] for col in df_A_75_PlantUML.columns])

# get dimensions
n = df_A_75_PlantUML.shape[0]
k = df_A_75_PlantUML.shape[1]

# effect size
W = stat / (n * (k - 1))

print("SET A - THRESHOLD: 75% for all size of plantUML")
print("Friedman statistic:", stat)
print("p-value:", f"{p:.6f}")
print("Kendall's W:", W)

SET A - THRESHOLD: 75% for all size of plantUML
Friedman statistic: 8.400000000000006
p-value: 0.014996
Kendall's W: 0.8400000000000005

In [33]:
stat, p = friedmanchisquare(*[df_A_100_PlantUML[col] for col in df_A_100_PlantUML.columns])

# get dimensions
n = df_A_100_PlantUML.shape[0]
k = df_A_100_PlantUML.shape[1]

# effect size
W = stat / (n * (k - 1))

print("SET A - THRESHOLD: 100% for all size of plantUML")
print("Friedman statistic:", stat)
print("p-value:", f"{p:.6f}")
print("Kendall's W:", W)

SET A - THRESHOLD: 100% for all size of plantUML
Friedman statistic: 7.176470588235304
p-value: 0.027647
Kendall's W: 0.7176470588235304

In [34]:
import scikit_posthocs as sp 

pairwise_A_25_PlantUML = sp.posthoc_nemenyi_friedman(df_A_25_PlantUML)
pairwise_A_50_PlantUML = sp.posthoc_nemenyi_friedman(df_A_50_PlantUML)
pairwise_A_75_PlantUML = sp.posthoc_nemenyi_friedman(df_A_75_PlantUML)
pairwise_A_100_PlantUML = sp.posthoc_nemenyi_friedman(df_A_100_PlantUML)

print("pairwise comparison at threshold 25% for PlantUML")
pairwise_A_25_PlantUML

pairwise comparison at threshold 25% for PlantUML

             PlantUML  PlantUMLx2  PlantUMLx10
PlantUML     1.000000    0.253784     0.004464
PlantUMLx2   0.253784    1.000000     0.253784
PlantUMLx10  0.004464    0.253784     1.000000

In [35]:
pairwise_A_50_PlantUML

             PlantUML  PlantUMLx2  PlantUMLx10
PlantUML     1.000000    0.415114     0.007507
PlantUMLx2   0.415114    1.000000     0.190612
PlantUMLx10  0.007507    0.190612     1.000000

In [36]:
print("pairwise comparison at threshold 75% for PlantUML")
pairwise_A_75_PlantUML

pairwise comparison at threshold 75% for PlantUML

             PlantUML  PlantUMLx2  PlantUMLx10
PlantUML     1.000000    0.609411     0.012310
PlantUMLx2   0.609411    1.000000     0.139405
PlantUMLx10  0.012310    0.139405     1.000000

In [37]:
print("pairwise comparison at threshold 100% for PlantUML")
pairwise_A_100_PlantUML

pairwise comparison at threshold 100% for PlantUML

             PlantUML  PlantUMLx2  PlantUMLx10
PlantUML     1.000000    0.986312     0.068887
PlantUMLx2   0.986312    1.000000     0.099292
PlantUMLx10  0.068887    0.099292     1.000000

In [38]:
#only for JSON:
df_A_25_JSON = df_A_25.loc[:,["JSON","JSONx2","JSONx10"]]
df_A_50_JSON = df_A_50.loc[:,["JSON","JSONx2","JSONx10"]]
df_A_75_JSON = df_A_75.loc[:,["JSON","JSONx2","JSONx10"]]
df_A_100_JSON = df_A_100.loc[:,["JSON","JSONx2","JSONx10"]]


df_A_25_JSON

       JSON    JSONx2   JSONx10
0  0.972000  0.888000  0.852000
1  0.944444  0.861111  0.851852
2  0.944444  0.861111  0.814815
3  0.944444  0.861111  0.916667
4  0.972222  0.861111  0.851852

In [39]:
stat, p = friedmanchisquare(*[df_A_25_JSON[col] for col in df_A_25_JSON.columns])

# get dimensions
n = df_A_25_JSON.shape[0]
k = df_A_25_JSON.shape[1]

# effect size
W = stat / (n * (k - 1))

print("SET A - TRHESHOLD: 25% for all size of JSON")
print("Friedman statistic:", stat)
print("p-value:", f"{p:.6f}")
print("Kendall's W:", W)

SET A - TRHESHOLD: 25% for all size of JSON
Friedman statistic: 8.400000000000006
p-value: 0.014996
Kendall's W: 0.8400000000000005

In [40]:
stat, p = friedmanchisquare(*[df_A_50_JSON[col] for col in df_A_50_JSON.columns])

# get dimensions
n = df_A_50_JSON.shape[0]
k = df_A_50_JSON.shape[1]

# effect size
W = stat / (n * (k - 1))

print("SET A - THRESHOLD: 50% for all size of JSON")
print("Friedman statistic:", stat)
print("p-value:", f"{p:.6f}")
print("Kendall's W:", W)

SET A - THRESHOLD: 50% for all size of JSON
Friedman statistic: 10.0
p-value: 0.006738
Kendall's W: 1.0

In [41]:
stat, p = friedmanchisquare(*[df_A_75_JSON[col] for col in df_A_75_JSON.columns])

# get dimensions
n = df_A_75_JSON.shape[0]
k = df_A_75_JSON.shape[1]

# effect size
W = stat / (n * (k - 1))

print("SET A - THRESHOLD: 75% for all size of JSON")
print("Friedman statistic:", stat)
print("p-value:", f"{p:.6f}")
print("Kendall's W:", W)

SET A - THRESHOLD: 75% for all size of JSON
Friedman statistic: 7.684210526315787
p-value: 0.021448
Kendall's W: 0.7684210526315787

In [42]:
stat, p = friedmanchisquare(*[df_A_100_JSON[col] for col in df_A_100_JSON.columns])

# get dimensions
n = df_A_100_JSON.shape[0]
k = df_A_100_JSON.shape[1]

# effect size
W = stat / (n * (k - 1))

print("SET A - THRESHOLD: 100% for all size of JSON")
print("Friedman statistic:", stat)
print("p-value:", f"{p:.6f}")
print("Kendall's W:", W)

SET A - THRESHOLD: 100% for all size of JSON
Friedman statistic: 10.0
p-value: 0.006738
Kendall's W: 1.0

In [43]:
pairwise_A_25_JSON = sp.posthoc_nemenyi_friedman(df_A_25_JSON)
pairwise_A_50_JSON = sp.posthoc_nemenyi_friedman(df_A_50_JSON)
pairwise_A_75_JSON = sp.posthoc_nemenyi_friedman(df_A_75_JSON)
pairwise_A_100_JSON = sp.posthoc_nemenyi_friedman(df_A_100_JSON)

print("pairwise comparison at threshold 25% for JSON")
pairwise_A_25_JSON

pairwise comparison at threshold 25% for JSON

             JSON    JSONx2   JSONx10
JSON     1.000000  0.139405  0.012310
JSONx2   0.139405  1.000000  0.609411
JSONx10  0.012310  0.609411  1.000000

In [44]:
print("pairwise comparison at threshold 50% for JSON")
pairwise_A_50_JSON

pairwise comparison at threshold 50% for JSON

             JSON    JSONx2   JSONx10
JSON     1.000000  0.253784  0.004464
JSONx2   0.253784  1.000000  0.253784
JSONx10  0.004464  0.253784  1.000000

In [45]:
print("pairwise comparison at threshold 75% for JSON")
pairwise_A_75_JSON

pairwise comparison at threshold 75% for JSON

             JSON    JSONx2   JSONx10
JSON     1.000000  0.253784  0.019679
JSONx2   0.253784  1.000000  0.509841
JSONx10  0.019679  0.509841  1.000000

In [46]:
print("pairwise comparison at threshold 100% for JSON")
pairwise_A_100_JSON

pairwise comparison at threshold 100% for JSON

             JSON    JSONx2   JSONx10
JSON     1.000000  0.253784  0.004464
JSONx2   0.253784  1.000000  0.253784
JSONx10  0.004464  0.253784  1.000000

In [47]:
# RQ2.3: compare set A and set B > no significant results

In [48]:
#compare set B to smallest models in set A

stat25, p25 = wilcoxon(df_A_25["PlantUML"], df_B_25["PlantUML-LM"])
stat50, p50 = wilcoxon(df_A_50["PlantUML"], df_B_50["PlantUML-LM"])
stat75, p75 = wilcoxon(df_A_75["PlantUML"], df_B_75["PlantUML-LM"])
stat100, p100 = wilcoxon(df_A_100["PlantUML"], df_B_100["PlantUML-LM"])

print("set A (PlantUML) vs set B at 25% threshold")
print("Statistic:", stat25)
print("p-value:", p25)
print("set A (PlantUML) vs set B at 50% threshold")
print("Statistic:", stat50)
print("p-value:", p50)
print("set A (PlantUML) vs set B at 75% threshold")
print("Statistic:", stat75)
print("p-value:", p75)
print("set A (PlantUML) vs set B at 100% threshold")
print("Statistic:", stat100)
print("p-value:", p100)

set A (PlantUML) vs set B at 25% threshold
Statistic: 1.0
p-value: 0.5
set A (PlantUML) vs set B at 50% threshold
Statistic: 0.0
p-value: 0.0625
set A (PlantUML) vs set B at 75% threshold
Statistic: 0.0
p-value: 0.0625
set A (PlantUML) vs set B at 100% threshold
Statistic: 0.0
p-value: 0.0625

In [49]:
#compare set B to x2 models in set A

stat25, p25 = wilcoxon(df_A_25["PlantUMLx2"], df_B_25["PlantUML-LM"])
stat50, p50 = wilcoxon(df_A_50["PlantUMLx2"], df_B_50["PlantUML-LM"])
stat75, p75 = wilcoxon(df_A_75["PlantUMLx2"], df_B_75["PlantUML-LM"])
stat100, p100 = wilcoxon(df_A_100["PlantUMLx2"], df_B_100["PlantUML-LM"])

print("set A (PlantUMLx2) vs set B at 25% threshold")
print("Statistic:", stat25)
print("p-value:", p25)
print("set A (PlantUMLx2) vs set B at 50% threshold")
print("Statistic:", stat50)
print("p-value:", p50)
print("set A (PlantUMLx2) vs set B at 75% threshold")
print("Statistic:", stat75)
print("p-value:", p75)
print("set A (PlantUMLx2) vs set B at 100% threshold")
print("Statistic:", stat100)
print("p-value:", p100)

set A (PlantUMLx2) vs set B at 25% threshold
Statistic: 3.0
p-value: 0.25
set A (PlantUMLx2) vs set B at 50% threshold
Statistic: 0.0
p-value: 0.0625
set A (PlantUMLx2) vs set B at 75% threshold
Statistic: 0.0
p-value: 0.0625
set A (PlantUMLx2) vs set B at 100% threshold
Statistic: 0.0
p-value: 0.0625

In [50]:
#compare set B to x10 models in set A

stat25, p25 = wilcoxon(df_A_25["PlantUMLx10"], df_B_25["PlantUML-LM"])
stat50, p50 = wilcoxon(df_A_50["PlantUMLx10"], df_B_50["PlantUML-LM"])
stat75, p75 = wilcoxon(df_A_75["PlantUMLx10"], df_B_75["PlantUML-LM"])
stat100, p100 = wilcoxon(df_A_100["PlantUMLx10"], df_B_100["PlantUML-LM"])

print("set A (PlantUMLx10) vs set B at 25% threshold")
print("Statistic:", stat25)
print("p-value:", p25)
print("set A (PlantUMLx10) vs set B at 50% threshold")
print("Statistic:", stat50)
print("p-value:", p50)
print("set A (PlantUMLx10) vs set B at 75% threshold")
print("Statistic:", stat75)
print("p-value:", p75)
print("set A (PlantUMLx10) vs set B at 100% threshold")
print("Statistic:", stat100)
print("p-value:", p100)

set A (PlantUMLx10) vs set B at 25% threshold
Statistic: 0.0
p-value: 0.0625
set A (PlantUMLx10) vs set B at 50% threshold
Statistic: 4.0
p-value: 0.5
set A (PlantUMLx10) vs set B at 75% threshold
Statistic: 0.0
p-value: 0.0625
set A (PlantUMLx10) vs set B at 100% threshold
Statistic: 0.0
p-value: 0.0625

In [51]:
#compare set B to smallest models in set A (JSON)

stat25, p25 = wilcoxon(df_A_25["JSON"], df_B_25["JSON-LM"])
stat50, p50 = wilcoxon(df_A_50["JSON"], df_B_50["JSON-LM"])
stat75, p75 = wilcoxon(df_A_75["JSON"], df_B_75["JSON-LM"])
stat100, p100 = wilcoxon(df_A_100["JSON"], df_B_100["JSON-LM"])

print("set A (JSON) vs set B at 25% threshold")
print("Statistic:", stat25)
print("p-value:", p25)
print("set A (JSON) vs set B at 50% threshold")
print("Statistic:", stat50)
print("p-value:", p50)
print("set A (JSON) vs set B at 75% threshold")
print("Statistic:", stat75)
print("p-value:", p75)
print("set A (JSON) vs set B at 100% threshold")
print("Statistic:", stat100)
print("p-value:", p100)

set A (JSON) vs set B at 25% threshold
Statistic: 6.0
p-value: 0.8125
set A (JSON) vs set B at 50% threshold
Statistic: 0.0
p-value: 0.0625
set A (JSON) vs set B at 75% threshold
Statistic: 0.0
p-value: 0.0625
set A (JSON) vs set B at 100% threshold
Statistic: 0.0
p-value: 0.0625

In [52]:
#compare set B to x2 models in set A (JSON)

stat25, p25 = wilcoxon(df_A_25["JSONx2"], df_B_25["JSON-LM"])
stat50, p50 = wilcoxon(df_A_50["JSONx2"], df_B_50["JSON-LM"])
stat75, p75 = wilcoxon(df_A_75["JSONx2"], df_B_75["JSON-LM"])
stat100, p100 = wilcoxon(df_A_100["JSONx2"], df_B_100["JSON-LM"])

print("set A (JSON) vs set B at 25% threshold")
print("Statistic:", stat25)
print("p-value:", p25)
print("set A (JSON) vs set B at 50% threshold")
print("Statistic:", stat50)
print("p-value:", p50)
print("set A (JSON) vs set B at 75% threshold")
print("Statistic:", stat75)
print("p-value:", p75)
print("set A (JSON) vs set B at 100% threshold")
print("Statistic:", stat100)
print("p-value:", p100)

set A (JSON) vs set B at 25% threshold
Statistic: 0.0
p-value: 0.0625
set A (JSON) vs set B at 50% threshold
Statistic: 4.5
p-value: 1.0
set A (JSON) vs set B at 75% threshold
Statistic: 0.0
p-value: 0.0625
set A (JSON) vs set B at 100% threshold
Statistic: 0.0
p-value: 0.0625

In [53]:
#compare set B to x10 models in set A (JSON)

stat25, p25 = wilcoxon(df_A_25["JSONx10"], df_B_25["JSON-LM"])
stat50, p50 = wilcoxon(df_A_50["JSONx10"], df_B_50["JSON-LM"])
stat75, p75 = wilcoxon(df_A_75["JSONx10"], df_B_75["JSON-LM"])
stat100, p100 = wilcoxon(df_A_100["JSONx10"], df_B_100["JSON-LM"])

print("set A (JSON) vs set B at 25% threshold")
print("Statistic:", stat25)
print("p-value:", p25)
print("set A (JSON) vs set B at 50% threshold")
print("Statistic:", stat50)
print("p-value:", p50)
print("set A (JSON) vs set B at 75% threshold")
print("Statistic:", stat75)
print("p-value:", p75)
print("set A (JSON) vs set B at 100% threshold")
print("Statistic:", stat100)
print("p-value:", p100)

set A (JSON) vs set B at 25% threshold
Statistic: 0.0
p-value: 0.0625
set A (JSON) vs set B at 50% threshold
Statistic: 1.0
p-value: 0.125
set A (JSON) vs set B at 75% threshold
Statistic: 0.0
p-value: 0.0625
set A (JSON) vs set B at 100% threshold
Statistic: 0.0
p-value: 0.0625

In [54]:
# RQ2.4: compare LLM provider > friedman test (only gpt5 vs gem-2.5-fl and gpt5 vs gpt4o are significant for set A)

In [55]:
# calculate friedman statistics for set A

stat, p = friedmanchisquare(*[df_prov_A[col] for col in df_prov_A.columns])
# get dimensions
n = df_prov_A.shape[0]
k = df_prov_A.shape[1]

# effect size
W = stat / (n * (k - 1))

print(df_prov_A)

print("SET A")
print("Friedman statistic:", stat)
print("p-value:", f"{p:.6f}")
print("Kendall's W:", W)

             gem-2.5-fl  gem-2.5-pro  gpt4o-mini  gpt5-mini
PlantUML       0.933333     0.977778    0.955556   1.000000
PlantUMLx2     0.861111     0.977778    0.944444   1.000000
PlantUMLx10    0.805556     0.988889    0.788889   0.988889
JSON           0.911111     0.955556    0.816667   0.988889
JSONx2         0.788889     0.844444    0.838889   0.877778
SET A
Friedman statistic: 13.285714285714281
p-value: 0.004058
Kendall's W: 0.8857142857142855

In [56]:
# calculate friedman statistics for set B

stat, p = friedmanchisquare(*[df_prov_B[col] for col in df_prov_B.columns])
# get dimensions
n = df_prov_B.shape[0]
k = df_prov_B.shape[1]

# effect size
W = stat / (n * (k - 1))

print(df_prov_B)

print("SET A")
print("Friedman statistic:", stat)
print("p-value:", f"{p:.6f}")
print("Kendall's W:", W)

             gem-2.5-fl  gem-2.5-pro  gpt4o-mini  gpt5-mini
PlantUML-LM    0.666667     0.866667    0.541667   0.916667
JSON-LM        0.375000     0.750000    0.550000   0.850000
SET A
Friedman statistic: 5.399999999999999
p-value: 0.144744
Kendall's W: 0.8999999999999998

In [57]:
pairwise_prov_A = sp.posthoc_nemenyi_friedman(df_prov_A)

print("pairwise comparison for set A")
pairwise_prov_A

pairwise comparison for set A

             gem-2.5-fl  gem-2.5-pro  gpt4o-mini  gpt5-mini
gem-2.5-fl     1.000000     0.158925    0.994838   0.011804
gem-2.5-pro    0.158925     1.000000    0.255856   0.760994
gpt4o-mini     0.994838     0.255856    1.000000   0.025015
gpt5-mini      0.011804     0.760994    0.025015   1.000000